### ISSUE TITLE
[enhancement]: Enhance Developer Experience with Docker Compose

### ISSUE THREAD

**Issue by KadlagAkash** [hiteshchoudhary/apihub#153]
### Description:

**Current setup poses challenges and hampers developer productivity**

1. Currently, our **Docker Compose** configuration uses **bind mounting** for the backend service, which requires 
    - managing the `node_modules` separately 
    - **rebuilding** the image whenever a new dependency is added to the project. 
   
2. Additionally, the **MongoDB** service **logs** clutter the terminal, making it difficult to focus on relevant information and causing unnecessary distraction.

### Proposed Changes:

1. Implement Docker Compose `watch` feature to automatically sync and rebuild, eliminating the need for `bind mounting` and manual management of `node_modules`.

2. Optimize MongoDB service by adding `--quiet` and `--logpath /dev/null` options to reduce log clutter.

### Use Case

After running `docker compose up --build`:

- ### Press `w` to Enable Watch 
   ![Screenshot 2024-05-02 at 11 27 50](https://github.com/hiteshchoudhary/apihub/assets/100425384/4e839bd7-0368-4cc2-b016-d073165f807d)

- ### Syncing `backend` service after changes in code
  ![Screenshot 2024-05-02 at 12 28 47](https://github.com/hiteshchoudhary/apihub/assets/100425384/d644c347-63b8-42cb-8821-d172e4f306f3)
  
- ### Rebuilding `backend` service after changes in dependencies
   ![Screenshot 2024-05-02 at 11 31 16](https://github.com/hiteshchoudhary/apihub/assets/100425384/9b514550-6852-4cc6-9691-1c105e98fe5e)

### Additional Information

- By implementing these changes, we aim to streamline the development workflow, improve developer productivity, and reduce the overhead of managing dependencies and logs.

- This enhancement aligns with our goal of providing a seamless development experience for contributors.

### Additional context or Information

- Initial Configuration:
   <details>
  <summary>docker-compose.yaml</summary>
 
    ```yaml
    version: '3.8'

    services:
      backend:
        image: freeapi-server
        build: .
        ports:
          - 8080:8080
        volumes:
          - ./:/usr/src/freeapi
          - /usr/src/freeapi/node_modules
        env_file:
          - ./.env
        depends_on:
          - mongodb
      mongodb:
        image: mongo
        container_name: mongodb
        volumes:
          - data:/data/db
        ports:
          - 27017:27017
    
    volumes:
      data:
    ```
</details>

- Proposed Configuration:
   <details>
  <summary>docker-compose.yaml</summary>
 
    ```yaml
    version: '3.8'

    services:
      backend:
        image: freeapi-server
        build: .
        ports:
          - 8080:8080
        env_file:
          - ./.env
        depends_on:
          - mongodb
        develop:
          watch:
            - action: sync
              path: .
              target: /usr/src/freeapi
              ignore:
                - node_modules/
            - action: rebuild
              path: ./package.json
    
      mongodb:
        image: mongo
        container_name: mongodb
        command: ['--quiet', '--logpath', '/dev/null']
        volumes:
          - data:/data/db
        ports:
          - 27017:27017
    
    volumes:
      data:
    ```
</details>

### Suggested Tools

- ### [Docker Compose Watch](https://docs.docker.com/compose/file-watch/)
  Docker Compose documentation for file watching feature.

- ### [Hands on](https://www.youtube.com/live/I-htDVxmFGM?feature=shared)
  Practical demo on implementing Docker Compose improvements.

### Labels:

- enhancement
- docker
- developer-experience
